### ISSUE TITLE
Failed to load auth plugin 'plugin-org.neo4j.example.auth.plugin.MyAuthPlugin'

### ISSUE THREAD

**Issue by VINNUSAURUS** [neo-technology/neo4j-example-auth-plugins#8]
Getting the below error when using on neo4j-enterprise:3.5.12

Updated the pom file to latest beta libraries

```
dbms.security.auth_enabled=true
dbms.security.auth_provider=plugin-org.test.neo4j.plugin.MyAuthPlugin
dbms.security.plugin.authentication_enabled=true
dbms.security.plugin.authorization_enabled=true
```

**my plugin jar file name :**_AuthPlugin.jar_

**pom file link** [https://drive.google.com/open?id=1hN6lQ8AP6c0-YPKUQMvWeCjAiTjBEPcX](url)

**neo4j.info** : [https://drive.google.com/open?id=1hCEltPmpnsa8RHZSnrXsbRekccc81RF5](url)

```
2019-11-22 10:21:29.895+0000 WARN [o.n.i.p.PageCache] The dbms.memory.pagecache.size setting has not been configured. It is recommended that this setting is always explicitly configured, to ensure the system has a balanced configuration. Until then, a computed heuristic value of 3109087232 bytes will be used instead. Run `neo4j-admin memrec` for memory configuration suggestions.
2019-11-22 10:21:30.297+0000 INFO [o.n.g.f.m.e.CommunityEditionModule] No locking implementation specified, defaulting to 'forseti'
2019-11-22 10:21:30.535+0000 ERROR [o.n.k.i.e.EnterpriseEditionModule] Failed to load security module. Caused by: Illegal configuration: Failed to load auth plugin 'plugin-org.neo4j.example.auth.plugin.MyAuthPlugin'. Illegal configuration: Failed to load auth plugin 'plugin-org.neo4j.example.auth.plugin.MyAuthPlugin'.
java.lang.IllegalArgumentException: Illegal configuration: Failed to load auth plugin 'plugin-org.neo4j.example.auth.plugin.MyAuthPlugin'.
	at org.neo4j.server.security.enterprise.auth.EnterpriseSecurityModule.illegalConfiguration(EnterpriseSecurityModule.java:352)
	at org.neo4j.server.security.enterprise.auth.EnterpriseSecurityModule.createPluginRealms(EnterpriseSecurityModule.java:300)
	at org.neo4j.server.security.enterprise.auth.EnterpriseSecurityModule.newAuthManager(EnterpriseSecurityModule.java:162)
	at org.neo4j.server.security.enterprise.auth.EnterpriseSecurityModule.setup(EnterpriseSecurityModule.java:89)
	at com.neo4j.security.CommercialSecurityModule.setup(CommercialSecurityModule.java:56)
	at org.neo4j.graphdb.factory.module.edition.AbstractEditionModule.setupSecurityModule(AbstractEditionModule.java:155)
	at com.neo4j.commercial.edition.CommercialEditionModule.createCommercialSecurityModule(CommercialEditionModule.java:134)
	at com.neo4j.commercial.edition.CommercialEditionModule.createSecurityModule(CommercialEditionModule.java:126)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:203)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
```

**Comment by moxious** [comment]
Thread here has the resolution, the dependencies were out of date.  But repo maintainers need to refresh this, it hasn't seen a commit in a while and it's still an often-referred to repo for examples

https://community.neo4j.com/t/failed-to-load-auth-plugin/12097

**Comment by vinnusaurus** [comment]
som
